### ISSUE TITLE
how to finetune my own trained model that not in the model zool?

### ISSUE THREAD

**Issue by visonpon** [Spandan-Madan/Pytorch_fine_tuning_Tutorial#1]
Hi, I have trained a model use my own data, now i want to  finetune it on anothter dataset ,but the trained model is not in the model zool , how can i do this finetune? can you give me some advice? thanks.

**Comment by Spandan-Madan** [comment]
Here's an outline - I'm assuming that you know how to load and save models (since you saved your custom model during training right?). If not, read here - https://discuss.pytorch.org/t/saving-and-loading-a-model-in-pytorch/2610. 

1) Using your first dataset and the custom model you mentioned and save the model. This concludes your pretraining.

2) Then, write a new file (to prevent confusion) in which the data loader reads the images you want to finetune on. Now, when you write the model, you'll again create a model using the same architecture as the pretraining step. Now, load the model you saved above. At this point, your dataloader is giving you the images of the second dataset, and model has parameters loaded that were trained on images from the first data set. 

3) Start training. Your model is being fine tuned. 

Makes sense?  Hope it helps :) If you're satisfied, feel free to close the issue. If not, ask your questions! :)

**Comment by Spandan-Madan** [comment]
Closing as answered same question on PyTorch forums too.
