### ISSUE TITLE
Code missing to freeze weights of pretrained layers

### ISSUE THREAD

**Issue by anjalishenoy** [Spandan-Madan/Pytorch_fine_tuning_Tutorial#8]
Hi,

Just noticed that your code loads the pre-trained model and updates the last hidden layer output size but doesn't freeze the model parameters so that they don't get updated while finetuning backprop.
This is particularly from this Pytorch Note https://pytorch.org/docs/0.3.1/notes/autograd.html which says that to fine tune you need to set the 'requires_grad' option to false :)

**Comment by seongkyun** [comment]
I've saw Pytorch's official tutorial and there're two kinds of fine tuning methods:
ConvNet as fixed feature extractor
Finetuning ConvNet.

You can see all the details in [https://pytorch.org/tutorials/beginner/transfer_learning_tutorial.html](url)

**Comment by Spandan-Madan** [comment]
Hi @anjalishenoy, as @seongkyun  mentioned, it's not necessary to freeze weights.

Essentially, freezing weights means you trust in the representation the earlier layers have learned, while letting all of them update means that you're just using the weights as a starting point.

The latter is slower on large datasets, and so people freeze them to train faster. For a small dataset, not freezing is marginally better because it won't take time to update all layers.
